version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: adamant-server
    volumes:
      - ./backend/conf:/app/conf
      - ./backend/schemas:/app/schemas
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: adamant-client
    ports:
      - "3000:80"
