FROM python:3.8
WORKDIR /app
RUN mkdir ./schemas
RUN mkdir ./temp-files
RUN mkdir ./conf

COPY backend/requirements.txt backend/api.py backend/mime-types-extensions.json backend/.flaskenv ./
#COPY backend/schemas/ ./schemas/
#RUN ls -la ./schemas/*
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "api:app"]